apiVersion: v1
kind: PersistentVolume
metadata:
  name: apiservice-log
  labels:
    type: nfs02
    usage: apiservice
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: *.nas.aliyuncs.com
    path: "/apiservice"