apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apiservice-log
  namespace: apiservice
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  selector:
    matchLabels:
      usage: "apiservice"