apiVersion: v1
kind: Service
metadata:
  name: dida-api
  namespace: apiservice
spec:
  selector:
    app: dida-api
  ports:
    - name: port25000
      protocol: TCP
      port: 25000
      targetPort: 25000
  type: NodePort