apiVersion: v1
kind: Service
metadata:
  name: base-api
  namespace: apiservice
spec:
  selector:
    app: base-api
  ports:
    - name: port25200
      protocol: TCP
      port: 25200
      targetPort: 25200
  type: NodePort