apiVersion: v1
kind: Service
metadata:
  name: dida-es-svc
spec:
  selector:
    app: es-node
  ports:
    - name: es-port9200
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: es-port9300
      protocol: TCP
      port: 9300
      targetPort: 9300
  type: NodePort
