apiVersion: v1
kind: Service
metadata:
  name: msg-center-sms
  namespace: pubservice
spec:
  selector:
    app: msg-center-sms
  ports:
    - name: port25101
      protocol: TCP
      port: 25101
      targetPort: 25101
  type: NodePort