apiVersion: v1
kind: Service
metadata:
  name: schedule-center
  namespace: pubservice
spec:
  selector:
    app: schedule-center
  ports:
    - name: port25300
      protocol: TCP
      port: 25300
      targetPort: 25300
  type: NodePort