apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-log
  labels:
    type: nfs01
    usage: pubservice
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: *.nas.aliyuncs.com
    path: "/pubservice"