apiVersion: v1
kind: Service
metadata:
  name: redis-svr
  namespace: pubservice
spec:
  selector:
    app: redis-svr
  ports:
    - name: port6379
      protocol: TCP
      port: 6379
      targetPort: 6379