apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-svr
  namespace: pubservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-svr
    spec:
      containers:
      - name: dida-mongo-server
        image: registry.dida100.cn:5000/mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "300m"
            memory: "512M"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

