apiVersion: v1
kind: Service
metadata:
  name: mongo-svr
  namespace: pubservice
spec:
  selector:
    app: mongo-svr
  ports:
    - name: port27017
      protocol: TCP
      port: 27017
      targetPort: 27017