apiVersion: v1
kind: Service
metadata:
  name: applog-svr
  namespace: pubservice
spec:
  selector:
    app: applog-svr
  ports:
    - name: port3000
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
