apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-svr
  namespace: pubservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-svr
    spec:
      containers:
      - name: dida-redis-server
        image: registry.dida100.cn:5000/redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "300m"
            memory: "512M"
      restartPolicy: Always
