apiVersion: v1
kind: Service
metadata:
  name: msg-center-api
  namespace: pubservice
spec:
  selector:
    app: msg-center-api
  ports:
    - name: port25100
      protocol: TCP
      port: 25100
      targetPort: 25100
  type: NodePort