apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-svr
  namespace: pubservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-svr
    spec:
      containers:
      - name: dida-rabbitmq-server
        image: registry.dida100.cn:5000/rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: "300m"
            memory: "512M"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

