apiVersion: v1
kind: Service
metadata:
  name: eureka-svr
  namespace: pubservice
spec:
  selector:
    app: eureka-svr
  ports:
    - name: port8761
      protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort