apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-log
  namespace: pubservice
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  selector:
    matchLabels:
      usage: "pubservice"