---
- name: Tomcat Cache Cleaning
  hosts: all
  remote_user: root
  tasks:
    - name: Clean Tomcat host cached memeory
      shell: sync;echo 1 > /proc/sys/vm/drop_caches
      when: ansible_nodename == "tomcat1" or
            ansible_nodename == "tomcat2"