---
- name: Initial docker service
  hosts: all
  remote_user: root
  tasks:
    - name: install docker daemon
      yum:
        name: docker
        state: present
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: create crt file fodler
      file:
        path: "/etc/docker/certs.d/registry.dida100.cn:5000"
        state: directory
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: copy crt to destination
      copy:
        src: "/opt/WORK/Cloud_scripts/Packages/domain.crt"
        dest: "/etc/docker/certs.d/registry.dida100.cn:5000/ca.crt"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: enable and start docker daemon
      shell: systemctl enable docker && systemctl start docker
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"