---
- name: GFW for Docker ENV
  remote_user: root
  hosts: all
  tasks:
    - name: setup privoxy proxy
      yum:
        name: privoxy,git
        state: present
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: install shadowsocks
      shell: "pip install git+https://github.com/shadowsocks/shadowsocks.git@master"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: config privoxy
      replace:
        path: /etc/privoxy/config
        regexp: '^#        forward-socks5t   /               127.0.0.1:9050 .'
        replace: '        forward-socks5t   /               127.0.0.1:1080 .'
#        after: '#      From the company example.com, direct connections are made to'
        backup: yes
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: run shadowsocks
      shell: "sslocal -s 47.91.21.156 -p 22 -k WeLoveShengxi666 -m aes-256-gcm -d start"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: start privoxy service
      systemd:
        name: privoxy
        state: started
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: setup docker PROXY dir
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: 0755
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: setup docker HTTP PROXY
      copy:
        src: "/opt/WORK/Cloud_scripts/Packages/http-proxy.conf"
        dest: "/etc/systemd/system/docker.service.d/"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: setup docker HTTPS PROXY
      copy:
        src: "/opt/WORK/Cloud_scripts/Packages/https-proxy.conf"
        dest: "/etc/systemd/system/docker.service.d/"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: docker daemon restart
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
#    - name: install kubelet-1.6.4-0, kubeadm-1.6.6-0 and kubernetes-cni
#      yum:
#        name: kubelet-1.6.4-0,kubeadm-1.6.6-0,kubernetes-cni
#        state: present
#      environment:
#        http_proxy: http://127.0.0.1:8118
#        https_proxy: http://127.0.0.1:8118
#      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: upload docker clean scripts
      copy:
        src: "/opt/WORK/Cloud_scripts/Packages/k8s_docker_clean.sh"
        dest: "/opt/"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: setup cron job
      cron:
        name: "docker cleaner"
        minute: "0"
        hour: "11"
        job: "source /opt/k8s_docker_clean.sh"
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: Global proxy setting
      lineinfile:
        path: /etc/profile
        line: "{{item}}"
      with_items:
        - 'export http_proxy=http://127.0.0.1:8118'
        - 'export https_proxy=https://127.0.0.1:8118'
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"