---
- name: init ECS OS after creating
  hosts: all
  remote_user: root
  tasks:
    - name: disable ssh password login
      replace:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'
        backup: yes
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: modify /etc/sysctl.conf to control tcp TIME_WAIT
      blockinfile:
        dest: /etc/sysctl.conf
        block: |
          ## add tcp resue, recycle and fin timeout
          net.ipv4.tcp_tw_reuse = 1
          net.ipv4.tcp_tw_recycle = 1
          net.ipv4.tcp_fin_timeout = 30
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: enable sysctl configuration
      command: /sbin/sysctl -p
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: install screen pacakge
      yum:
        name: screen
        state: present
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: install iotop tools
      yum:
        name: iotop
        state: present
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: prepare TCP_BBR, change kernel
      shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org && rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm && yum --enablerepo=elrepo-kernel install kernel-ml -y
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: prepare TCP_BBR, change grub
      shell: egrep ^menuentry /etc/grub2.cfg | cut -f 2 -d \' && grub2-set-default 0 && reboot
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: pause 30s for boot up
      pause:
        seconds: 30
    - name: prepare TCP_BBR, setup BBR
      shell: modprobe tcp_bbr && echo "tcp_bbr" >> /etc/modules-load.d/modules.conf && echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf && echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
    - name: prepare TCP_BBR, enable BBR
      shell: sysctl -p
      when: ansible_nodename != "iZbp17dp6g4m63xlrqb41xZ"
